# Generated by Django 3.0.5 on 2021-09-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0002_homeworkfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkFile',
        ),
    ]
