# Generated by Django 3.0.5 on 2021-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_delete_homeworkfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name_other',
            field=models.CharField(default='', max_length=256),
        ),
    ]
