# Generated by Django 3.0.5 on 2021-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_file_file_name_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('src', 'src'), ('bit', 'bit'), ('log', 'log'), ('report', 'report'), ('other', 'other'), ('unknown', 'unknown')], max_length=8),
        ),
    ]
