# Generated by Django 3.0.5 on 2021-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0005_auto_20211009_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
