apiVersion: v1
kind: Service
metadata:
  name: frext-online-svc-outer
spec:
  type: NodePort
  selector:
    app: frext-online-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30180

---

apiVersion: v1
kind: Service
metadata:
  name: frext-online-svc
spec:
  selector:
    app: frext-online-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-online-test
  labels:
    app: frext-online-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-online-test
  template:
    metadata:
      labels:
        app: frext-online-test
    spec:
      serviceAccountName:
        frext
      initContainers:
      - name: volume-mount-hack
        image: debian:stable-slim
        command: [ "sh", "-c", "chown -R 1001:1001 /nexus" ]
        volumeMounts:
        - name: fs
          mountPath: /nexus
      containers:
      - name: frext-online-test
        image: wxwd14388/frext-testing-test:v0.0.9
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 4;done"]
        volumeMounts:
        - mountPath: /tmp/FrexT
          name: frext-job
        - mountPath: /data/FrexT
          name: fs
        ports:
          - containerPort: 8080
      volumes:
        - name: frext-job
          hostPath:
            path: /root/FrexT
            type: Directory
        - name: fs
          hostPath:
            path: /root/FrexT_data/frext-file-system/log_online
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: frext/role
                    operator: In
                    values:
                      - file-system
