# Generated by Django 3.0.5 on 2021-09-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_coursefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='delete_time',
        ),
    ]
