# Generated by Django 3.0.5 on 2021-09-28 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
        ('File', '0004_remove_coursefile_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkfile',
            name='course_template_experiment',
        ),
        migrations.AddField(
            model_name='homeworkfile',
            name='class_homework',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Class.ClassHomework'),
            preserve_default=False,
        ),
    ]
