# Generated by Django 3.0.5 on 2021-10-23 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=32)),
                ('url_path', models.CharField(max_length=128)),
                ('raw_uri', models.CharField(max_length=256)),
                ('body', models.TextField(default='')),
                ('action', models.CharField(default='', max_length=256)),
                ('other_info', models.TextField(default='')),
                ('login_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.LoginRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
