# Generated by Django 3.0.5 on 2021-09-27 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheClass',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('enter_time', models.DateTimeField(auto_now_add=True)),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.TheClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
        migrations.CreateModel(
            name='ClassHomework',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('course_template_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseTemplateExperiment')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.TheClass')),
            ],
        ),
    ]
