# Generated by Django 3.0.5 on 2021-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhomework',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
