# Generated by Django 3.0.5 on 2021-09-29 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('Experiment', '0006_auto_20210928_0958'),
        ('Class', '0002_auto_20210928_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkExperiment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('class_homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassHomework')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiment.Experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
